#!/bin/bash


## Load the required modules
module load mpt
module load intel-compilers-19

## compile


## compile with MPI:
mpicxx heat_parallel.cpp  -o heat_parallel.exe

## remove object files if there is any!:
# rm *.mod
# rm *.o

